#!/usr/bin/env python
# ec2-instance-status
import argparse
import os
import subprocess
import sys
import logging

formatter = logging.Formatter()
logging.basicConfig(stream=sys.stderr, level=logging.INFO,
                    format='%(levelname)s: %(message)s')
log = logging.getLogger('ec2-instance-status')


parser = argparse.ArgumentParser(description='Copies a local file or ec2 object to another location locally or in ec2.')
parser.add_argument('instance_ids', help='One or more instance IDs.')
args = parser.parse_args()

COMMAND = ["aws", "ec2", "describe-instance-status", "--instance-ids", args.instance_ids]


if os.getenv("RD_CONFIG_DRYRUN") == "true":
    COMMAND.append("--dry-run")

if "RD_CONFIG_FILTERS" in os.environ:
    COMMAND.append("--filters")
    COMMAND.append(os.getenv("RD_CONFIG_FILTERS"))
if "RD_CONFIG_CLI_INPUT_JSON" in os.environ:
    COMMAND.append("--cli-input-json")
    COMMAND.append(os.getenv("RD_CONFIG_CLI_INPUT_JSON"))
if "RD_CONFIG_GENERATE_CLI_SKELETON" in os.environ:
    COMMAND.append("--generate-cli-skeleton")
    COMMAND.append(os.getenv("RD_CONFIG_GENERATE_CLI_SKELETON"))

if "RD_CONFIG_ACCESS_KEY" in os.environ:
    os.environ["AWS_ACCESS_KEY_ID"] = os.environ["RD_CONFIG_ACCESS_KEY"]
if "RD_CONFIG_SECRET_ACCESS_KEY" in os.environ:
	os.environ["AWS_SECRET_ACCESS_KEY"] = os.environ["RD_CONFIG_SECRET_ACCESS_KEY"]
if "RD_CONFIG_DEFAULT_REGION" in os.environ:
	os.environ["AWS_DEFAULT_REGION"] = os.environ["RD_CONFIG_DEFAULT_REGION"]

log.info("Executing: '%s' ..." % ' '.join(COMMAND))

try:
    retcode = subprocess.call(COMMAND)
    sys.exit(retcode)
except OSError as e:
    print >>sys.stderr, "Command error:", e
    sys.exit(1)
# Done